require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JamsController do

  # This should return the minimal set of attributes required to create a valid
  # Jam. As you add validations to Jam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JamsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all jams as @jams" do
      jam = Jam.create! valid_attributes
      get :index, {}, valid_session
      assigns(:jams).should eq([jam])
    end
  end

  describe "GET show" do
    it "assigns the requested jam as @jam" do
      jam = Jam.create! valid_attributes
      get :show, {:id => jam.to_param}, valid_session
      assigns(:jam).should eq(jam)
    end
  end

  describe "GET new" do
    it "assigns a new jam as @jam" do
      get :new, {}, valid_session
      assigns(:jam).should be_a_new(Jam)
    end
  end

  describe "GET edit" do
    it "assigns the requested jam as @jam" do
      jam = Jam.create! valid_attributes
      get :edit, {:id => jam.to_param}, valid_session
      assigns(:jam).should eq(jam)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Jam" do
        expect {
          post :create, {:jam => valid_attributes}, valid_session
        }.to change(Jam, :count).by(1)
      end

      it "assigns a newly created jam as @jam" do
        post :create, {:jam => valid_attributes}, valid_session
        assigns(:jam).should be_a(Jam)
        assigns(:jam).should be_persisted
      end

      it "redirects to the created jam" do
        post :create, {:jam => valid_attributes}, valid_session
        response.should redirect_to(Jam.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jam as @jam" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jam.any_instance.stub(:save).and_return(false)
        post :create, {:jam => { "name" => "invalid value" }}, valid_session
        assigns(:jam).should be_a_new(Jam)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jam.any_instance.stub(:save).and_return(false)
        post :create, {:jam => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jam" do
        jam = Jam.create! valid_attributes
        # Assuming there are no other jams in the database, this
        # specifies that the Jam created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Jam.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => jam.to_param, :jam => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested jam as @jam" do
        jam = Jam.create! valid_attributes
        put :update, {:id => jam.to_param, :jam => valid_attributes}, valid_session
        assigns(:jam).should eq(jam)
      end

      it "redirects to the jam" do
        jam = Jam.create! valid_attributes
        put :update, {:id => jam.to_param, :jam => valid_attributes}, valid_session
        response.should redirect_to(jam)
      end
    end

    describe "with invalid params" do
      it "assigns the jam as @jam" do
        jam = Jam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jam.any_instance.stub(:save).and_return(false)
        put :update, {:id => jam.to_param, :jam => { "name" => "invalid value" }}, valid_session
        assigns(:jam).should eq(jam)
      end

      it "re-renders the 'edit' template" do
        jam = Jam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jam.any_instance.stub(:save).and_return(false)
        put :update, {:id => jam.to_param, :jam => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jam" do
      jam = Jam.create! valid_attributes
      expect {
        delete :destroy, {:id => jam.to_param}, valid_session
      }.to change(Jam, :count).by(-1)
    end

    it "redirects to the jams list" do
      jam = Jam.create! valid_attributes
      delete :destroy, {:id => jam.to_param}, valid_session
      response.should redirect_to(jams_url)
    end
  end

end
